apiVersion: apps/v1
kind: Deployment
metadata:
  name: pipo-frontend
  namespace: pipo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pipo-frontend
  template:
    metadata:
      labels:
        app: pipo-frontend
    spec:
      containers:
        - name: frontend
          image: pipo-frontend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
